### ISSUE TITLE
Is the microphone supposed to work?

### ISSUE THREAD

**Issue by guyou** [lolstring/gnome-shell-extension-mycroft#20]
I'm not sure about this functionality: is the microphone supposed to work?

Currently, I have the microphone symbol displayed, but without any round (nor cross) near it. I do not understand what does it mean. Clicking on it do nothing.

Reading code does not help me.

Can you give me an help?

**Comment by AIIX** [comment]
The extension is broken because of Libsoup's implementation of websockets, that causes system freezing and system hang issues while connecting to Mycroft. Also this extension requires you to have a local copy of mycroft-core which can be found at https://github.com/MycroftAI/mycroft-core. Microphone settings and audio is handled by core and you should check if the audio is working there

**Comment by guyou** [comment]
Initially, I imagined that the extension is responsible of recording voice and then transmitting this record to mycroft-core. But after reading a lot of code, it seems it is not the way Mycroft work.

Thanks for explanations.
