### ISSUE TITLE
Use pkcon instead of apt-get, dnf

### ISSUE THREAD

**Issue by afranke** [lolstring/gnome-shell-extension-mycroft#7]
`pkcon` is part of PackageKit, an abstraction of package managers. It is present by default in most modern distributions including Fedora and Ubuntu, and allows one to use a single command that will work on all systems, while still integrating with the system.

What’s more, pkcon use PolicyKit to get the required priviledges, so one doesn’t need to use sudo or equivalents.

The current code could be simplified a lot and the required command for installation would simply be `pkcon install git`.

**Comment by afranke** [comment]
I forgot to mention that as a bonus you’ll get something that works for even more distributions.

**Comment by lolstring** [comment]
Just looked into it, pkcon could be added in the future. But, mycroft-core has individual build files(build_host_setup_*.sh) for each distribution since requirements vary so I do have to segregate it anyways. 

I will leave it as it is till the build files are either put into one script or the build process changes. 

Thank you though, learnt something new :)
